/*
 * Copyright (c) 1998-2023 Kx Systems Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the
 * License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */

import {
  CompletionItem,
  CompletionItemKind,
  CompletionItemProvider,
  CompletionList,
  ProviderResult,
} from "vscode";
import { ext } from "../extensionVariables";
import { KdbNode } from "./kdbTreeProvider";

export class CompletionProvider implements CompletionItemProvider {
  provideCompletionItems(): ProviderResult<
    CompletionItem[] | CompletionList<CompletionItem>
  > {
    if (ext.connectionNode instanceof KdbNode) {
      const items: CompletionItem[] = [];
      [ext.functions, ext.tables, ext.variables].forEach((group) =>
        group.forEach((item) =>
          items.push({
            label: item,
            detail: `${ext.connectionNode?.label}`,
            insertText: item,
            kind: CompletionItemKind.Variable,
          }),
        ),
      );
      return items;
    }
    return qLangParserItems;
  }
}

const qLangParserItems: CompletionItem[] = [
  {
    label: "abs",
    detail: "absolute value",
    documentation: "abs[numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "acos",
    detail: "arccosine",
    documentation: "acos[numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "aj",
    detail: "as-of join(boundary time from LHS)",
    documentation: "aj[syms;table;table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "aj0",
    detail: "as-of join(actual time from RHS)",
    documentation: "aj0[syms;table;table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "ajf",
    detail: "as-of join(only fill null values from LHS)",
    documentation: "ajf[syms;table;table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "ajf0",
    detail: "as-of join(only fill null values from RHS)",
    documentation: "ajf0[syms;table;table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "all",
    detail: ":true if all true",
    documentation: "all[numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "and",
    detail: "AND(min)",
    documentation: "and[numbers;numbers]   ",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "any",
    detail: ":true if any true",
    documentation: "any[numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "asc",
    detail: "ascending sort",
    documentation: "asc[list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "asin",
    detail: "arcsine",
    documentation: "asin[numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "asof",
    detail: "as-of join",
    documentation: "asof[table;<table|dict>]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "atan",
    detail: "arctangent",
    documentation: "atan[numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "attr",
    detail: "attribute",
    documentation: "attr[any]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "avg",
    detail: "arithmetic mean",
    documentation: "avg[numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "avgs",
    detail: "running average",
    documentation: "avgs[numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "bin",
    detail: "binary search(<=x)",
    documentation: "bin[numbers!;numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "binr",
    detail: "binary search right(>=x)",
    documentation: "binr[numbers!;numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "ceiling",
    detail: "round up",
    documentation: "ceiling[numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "cols",
    detail: "column names",
    documentation: "cols[table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "cor",
    detail: "correlation",
    documentation: "cor[numbers;numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "cos",
    detail: "cosine",
    documentation: "cos[numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "count",
    detail: "count items",
    documentation: "count[any]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "cov",
    detail: "covariance",
    documentation: "cov[numbers;numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "cross",
    detail: "cross product",
    documentation: "cross[list;list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "cut",
    detail: "cut into lists",
    documentation: "cut[ints;list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "delete",
    detail: "delete rows or columns from a table",
    documentation: "delete [col1,col2] from t [where cond]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "deltas",
    detail: "difference between list items",
    documentation: "deltas[<default;>numbers or temporals]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "desc",
    detail: "descending sort",
    documentation: "desc[list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "dev",
    detail: "deviation",
    documentation: "dev[numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "differ",
    detail: "find changes by comparing to next",
    documentation: "differ[list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "distinct",
    detail: "remove duplicates",
    documentation: "distinct[list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "div",
    detail: "integer division",
    documentation: "div[numbers;numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "do",
    detail: "evaluate expression repeatedly",
    documentation: "do[times;e1;e2...]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "dsave",
    detail: "save global tables to disk",
    documentation: "dsave[hsym;syms]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "each",
    detail: "each iterator",
    documentation: " each[v1;list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "ej",
    detail: "equal join",
    documentation: "ej[syms;table;table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "ema",
    detail: "exponential moving average",
    documentation: "ema[smoothing factors;numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "enlist",
    detail: "make a list",
    documentation: "enlist[any]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "eval",
    detail: "evaluate a parse tree",
    documentation: "eval[list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "except",
    detail: "exclude items",
    documentation: "except[list;exclusions]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "exec",
    detail: "select rows and columns as a list or dict",
    documentation: "exec col1,col2 [by col3] from t [where cond]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "exit",
    detail: "terminate with code number",
    documentation: "exit[int]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "exp",
    detail: "power of the base of the natural logarithm",
    documentation: "exp[numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "fby",
    detail: "apply aggregate to groups",
    documentation: "(function;list) fby group|([]group1;group2)",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "fills",
    detail: "replace nulls with preceding non-nulls",
    documentation: "fills[list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "first",
    detail: "first item",
    documentation: "first[any]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "fkeys",
    detail: "foreign-key columns",
    documentation: "fkeys[table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "flip",
    detail: "transposed",
    documentation: "flip[list|dict|table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "floor",
    detail: "round down",
    documentation: "floor[numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "get",
    detail: "read or memory-map a variable or kdb+ file",
    documentation: "get[sym|file]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "getenv",
    detail: "get an environment variable",
    documentation: "getenv[sym]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "group",
    detail: "group items into a dict",
    documentation: "group[list|dict]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "gtime",
    detail: "convert to UTC",
    documentation: "gtime[timestamps]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "hclose",
    detail: "close a file or process handle",
    documentation: "hclose[handle]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "hcount",
    detail: "size of a file in bytes",
    documentation: "hcount[file]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "hdel",
    detail: "delete a file or folder",
    documentation: "hdel[file|dir]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "hopen",
    detail: "open a file or process handle",
    documentation: "hopen[file|socket|string<;timeout ms>]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "hsym",
    detail: "convert to process symbols",
    documentation: "hsym[syms]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "iasc",
    detail: "ascending grade",
    documentation: "iasc[list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "idesc",
    detail: "descending grade",
    documentation: "idesc[list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "if",
    detail: "evaluate expressions if true",
    documentation: "if[test;e1;e2...]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "ij",
    detail: "inner join",
    documentation: "ij[table;table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "ijf",
    detail: "inner join(fill null values from RHS)",
    documentation: "ijf[table;table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "in",
    detail: "test if items in the list",
    documentation: "in[items;list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "insert",
    detail: "insert or append records",
    documentation: "insert[table;records]|insert[undefined sym;table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "inter",
    detail: "intersection",
    documentation: "inter[list;list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "inv",
    detail: "matrix inverse",
    documentation: "inv[matrix]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "key",
    detail: "key of a dict",
    documentation: "key[sym|dict]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "keys",
    detail: "key columns of a table",
    documentation: "keys[table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "last",
    detail: "last item",
    documentation: "last[x]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "like",
    detail: "match text",
    documentation: "like[syms|strings|dict<any!syms|strings>;string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "lj",
    detail: "left join",
    documentation: "lj[table;keyed table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "ljf",
    detail: "left join(ignore nulls from RHS)",
    documentation: "ljf[table;keyed table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "load",
    detail: "load binary file|dir",
    documentation: "load[file|dir]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "log",
    detail: "natural logarithm",
    documentation: "log[numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "lower",
    detail: "lower case",
    documentation: "lower[<symbols|strings>]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "lsq",
    detail: "least squares",
    documentation: "lsq[matrixes;matrixes]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "ltime",
    detail: "convert to local timestamp",
    documentation: "ltime[ts]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "ltrim",
    detail: "trim leading spaces",
    documentation: "ltrim[string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "mavg",
    detail: "moving average",
    documentation: "mavg[int;numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "max",
    detail: "maximum",
    documentation: "max[numbers|characters|temporals]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "maxs",
    detail: "running maximums",
    documentation: "maxs[<default;>numbers|characters|temporals]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "mcount",
    detail: "moving count",
    documentation: "mcount[int;list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "md5",
    detail: "message digest hash",
    documentation: "md5[string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "mdev",
    detail: "moving deviations",
    documentation: "mdev[int;numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "med",
    detail: "median",
    documentation: "med[numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "meta",
    detail: "metadata for a table",
    documentation: "meta[table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "min",
    detail: "minimum",
    documentation: "min[numbers|characters|temporals]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "mins",
    detail: "running minimums",
    documentation: "maxs[<default;>numbers|characters|temporals]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "mmax",
    detail: "moving maximums",
    documentation: "mmax[int;numbers|characters|temporals]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "mmin",
    detail: "moving minimums",
    documentation: "mmin[int;numbers|characters|temporals]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "mmu",
    detail: "matrix multiply",
    documentation: "mmu[matrix;matrix]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "mod",
    detail: "modulus",
    documentation: "mod[divisors;dividends]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "msum",
    detail: "moving sums",
    documentation: "msum[int;numbers|characters|temporals]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "neg",
    detail: "negate",
    documentation: "neg[numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "next",
    detail: "shift each to next(last is null)",
    documentation: "next[list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "not",
    detail: "1b if non-zero else 0b",
    documentation: "not[numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "null",
    detail: "is null",
    documentation: "null[x]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "over",
    detail: "apply progressively and :last evaluation",
    documentation: "over[v1|vv;list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "parse",
    detail: "parse a string to ast",
    documentation: "parse[string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "peach",
    detail: "each parallel iterator",
    documentation: " x peach list",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "pj",
    detail: "plus join",
    documentation: "pj[table;keyed table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "prd",
    detail: "product",
    documentation: "prd[numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "prds",
    detail: "running products",
    documentation: "prds[numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "prev",
    detail: "shift each to prev(first is null)",
    documentation: "prev[list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "prior",
    detail: "apply to each item and its preceding item",
    documentation: "prior[v2|vv;list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "rand",
    detail: "pick randomly",
    documentation: "rand[number]|rand[list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "rank",
    detail: "position in the sorted list",
    documentation: "rank[list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "ratios",
    detail: "running ratios",
    documentation: "ratios[<default;>numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "raze",
    detail: "flat a list",
    documentation: "raze[list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "read0",
    detail: "read text from a file or process handle",
    documentation: "read0[hsym|(hsym;offset;length)]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "read1",
    detail: "read bytes from a file or process handle",
    documentation: "read1[hsym|(hsym;offset;length)]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "reciprocal",
    detail: "reciprocal",
    documentation: "reciprocal[numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "reval",
    detail: "evaluate a parse tree in read only mode",
    documentation: "reval[list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "reverse",
    detail: "reverse a list",
    documentation: "reverse[list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "rload",
    detail: "load a splayed table",
    documentation: "rload[dir]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "rotate",
    detail: "rotate a list",
    documentation: "rotate[int;list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "rsave",
    detail: "save as a splayed table to pwd",
    documentation: "rsave[sym]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "rtrim",
    detail: "trim tailing spaces",
    documentation: "rtrim[string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "save",
    detail: "save to pwd",
    documentation: "save[sym]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "scan",
    detail: "apply progressively and :all evaluations",
    documentation: "scan[v1|vv;list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "scov",
    detail: "sample covariance",
    documentation: "scov[numbers;numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "sdev",
    detail: "sample standard deviation",
    documentation: "sdev[numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "select",
    detail: "select rows and columns as a table",
    documentation: "select col1,col2 [by col3] from table [where cond]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "set",
    detail: "assign a value to a variable or file",
    documentation: "set[sym|file|dir;any]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "setenv",
    detail: "set an environment variable",
    documentation: "setenv[sym;string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "show",
    detail: "display at the console",
    documentation: "show[any]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "signum",
    detail: "sign",
    documentation: "signum[numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "sin",
    detail: "sine",
    documentation: "sin[numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "sqrt",
    detail: "square root",
    documentation: "sqrt[numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "ss",
    detail: "string search",
    documentation: "ss[string;pattern]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "ssr",
    detail: "string search and replace",
    documentation: "ssr[string;pattern;string|function]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "string",
    detail: "cast to string",
    documentation: "string[any]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "sublist",
    detail: "select a sublist",
    documentation: "sublist[int;list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "sum",
    detail: "total",
    documentation: "sum[numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "sums",
    detail: "running sums",
    documentation: "sums[numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "sv",
    detail: "concatenate strings|syms",
    documentation: "sv[string;strings]|sv[`;syms]|sv[numbers;numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "svar",
    detail: "sample variance",
    documentation: "svar[numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "system",
    detail: "execute a system command",
    documentation: "system[string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "tables",
    detail: "list tables",
    documentation: "tables[namespace sym]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "tan",
    detail: "tangent",
    documentation: "tan[numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "til",
    detail: "generate long sequence",
    documentation: "til[long]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "trim",
    detail: "trim leading and trailing spaces",
    documentation: "trim[string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "type",
    detail: "datatype",
    documentation: "type[x]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "uj",
    detail: "union join",
    documentation: "uj[table;table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "ujf",
    detail: "union join(ignore nulls from RHS)",
    documentation: "ujf[table;table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "ungroup",
    detail: "ungroup list type columns in a table into rows",
    documentation: "ungroup[table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "union",
    detail: "union of two lists",
    documentation: "union[list;list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "update",
    detail: "amend table|dict",
    documentation: "update col1,col2 [by col3] from table [where cond]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "upper",
    detail: "upper case",
    documentation: "upper[sym|string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "upsert",
    detail: "add new records",
    documentation: "upsert[table|sym;records|table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "value",
    detail: "value",
    documentation: "value[symbol|string|list|dict]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "var",
    detail: "variance",
    documentation: "var[numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "view",
    detail: "expression defining a view",
    documentation: "view[sym]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "views",
    detail: "list veiws defined",
    documentation: "views[namespace sym]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "vs",
    detail: "split string|symbol",
    documentation: "vs[string;string]|sv[`;sym|dir]|sv[number;number]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "wavg",
    detail: "weighted average",
    documentation: "wavg[weights;numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "where",
    detail: "to indices",
    documentation: "where[numbers]|where[booleans]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "while",
    detail: "evaluate expression repeatedly",
    documentation: "while[test;e1;e2...]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "within",
    detail: "check bounds",
    documentation: "within[list;range]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "wj",
    detail: "window join(consider prevailing quotes before window)",
    documentation: "wj[windows;syms;table;(table;(aggr;sym)<;(aggr;sym)>)]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "wj1",
    detail: "window join(consider quotes after entry to the window)",
    documentation: "wj1[windows;syms;table;(table;(aggr;sym)<;(aggr;sym)>)]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "wsum",
    detail: "weighted sum",
    documentation: "wsum[weights;numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "xasc",
    detail: "ascending sort table by columns",
    documentation: "xasc[syms;table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "xcol",
    detail: "rename columns",
    documentation: "xcol[syms;table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "xcols",
    detail: "reorder columns",
    documentation: "xcols[syms;table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "xdesc",
    detail: "descending sort table by columns",
    documentation: "xdesc[syms;table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "xexp",
    detail: "power",
    documentation: "xexp[bases;powers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "xlog",
    detail: "logarithm",
    documentation: "xlog[bases;numbers]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "xprev",
    detail: "shift each to prev by number",
    documentation: "xprev[int;list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "xbar",
    detail: "round down to multiples",
    documentation: "xbar[base;numbers|termporals]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "xgroup",
    detail: "group by values in selected columns",
    documentation: "xgroup[syms;table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "xkey",
    detail: "set key columns",
    documentation: "xkey[syms;table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: "xrank",
    detail: "group by value",
    documentation: "xrank[int;list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.br",
    detail: "linebreak",
    documentation: ".h.br",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.c0",
    detail: "web color",
    documentation: ".h.c0",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.c1",
    detail: "web color",
    documentation: ".h.c1",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.cd",
    detail: "CSV from data",
    documentation: ".h.cd[table|list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.code",
    detail: "code after Tab",
    documentation: ".h.code[string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.d",
    detail: "delimiter",
    documentation: ".h.d",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.ed",
    detail: "Excel from data",
    documentation: ".h.ed[table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.edsn",
    detail: "Excel from tables",
    documentation: ".h.edsn[sheet syms!tables]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.fram",
    detail: "frame",
    documentation:
      ".h.fram[title string;strings;(left frame strings;right frame strings)]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.ha",
    detail: "anchor",
    documentation: ".h.ha[url;string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.hb",
    detail: "anchor target",
    documentation: ".h.hb[url;string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.hc",
    detail: "escape lt",
    documentation: ".h.hc[string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.he",
    detail: "HTTP 400",
    documentation: ".h.he[string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.hn",
    detail: "HTTP response",
    documentation: ".h.hn[status code string;content type sym;content string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.HOME",
    detail: "webserver root",
    documentation: ".h.HOME",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.hp",
    detail: "HTTP response pre",
    documentation: ".h.hp[string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.hr",
    detail: "horizontal rule",
    documentation: ".h.hr[string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.ht",
    detail: "Marqdown to HTML",
    documentation: ".h.ht[file]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.hta",
    detail: "start tag",
    documentation: ".h.hta[HTML tag sym;attributes!values]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.htac",
    detail: "element",
    documentation: ".h.htac[HTML tag sym;attributes!values;content]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.htc",
    detail: "element",
    documentation: ".h.htc[HTML tag sym;content]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.html",
    detail: "document",
    documentation: ".h.html[html body string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.http",
    detail: "hyperlinks",
    documentation: ".h.http[string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.hu",
    detail: "URI escape",
    documentation: ".h.hu[string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.hug",
    detail: "URI map",
    documentation: ".h.hug[string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.hy",
    detail: "HTTP response content",
    documentation: ".h.hy[http content type sym;string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.iso8601",
    detail: "ISO timestamp",
    documentation: ".h.iso8601[nanoseconds]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.jx",
    detail: "table",
    documentation: ".h.jx[offset;table sym]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.logo",
    detail: "Kx logo",
    documentation: ".h.logo",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.nbr",
    detail: "no break",
    documentation: ".h.nbr[string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.pre",
    detail: "pre",
    documentation: ".h.pre[strings]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.sa",
    detail: "anchor style",
    documentation: ".h.sa",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.sb",
    detail: "body style",
    documentation: ".h.sb",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.sc",
    detail: "URI-safe",
    documentation: ".h.sc",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.td",
    detail: "TSV from data",
    documentation: ".h.td[table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.text",
    detail: "paragraphs",
    documentation: ".h.text[strings]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.tx",
    detail: "filetypes",
    documentation: ".h.tx",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.ty",
    detail: "MIME types",
    documentation: ".h.ty",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.uh",
    detail: "URI unescape",
    documentation: ".h.uh[string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.val",
    detail: "value",
    documentation: ".h.val:{[expression]}",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.xd",
    detail: "XML",
    documentation: ".h.xd[table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.xmp",
    detail: "XMP",
    documentation: ".h.xmp[strings]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.xs",
    detail: "XML escape",
    documentation: ".h.xs[string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".h.xt",
    detail: "JSON",
    documentation: ".h.xt[`json;json string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".j.j",
    detail: "serialize",
    documentation: ".j.j[any]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".j.k",
    detail: "deserialize",
    documentation: ".j.k[string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".j.jd",
    detail: "serialize infinity",
    documentation: ".j.jd[any;()!()|(!). 1#'`null0w,1b]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.a",
    detail: "lowercase alphabet",
    documentation: ".Q.a",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.A",
    detail: "uppercase alphabet",
    documentation: ".Q.A",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.addmonths",
    detail: "add months to date",
    documentation: ".Q.addmonths[dates;ints]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.addr",
    detail: "IP address",
    documentation: ".Q.addr[sym]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.b6",
    detail: "bicameral-alphanums",
    documentation: ".Q.b6",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.bt",
    detail: "backtrace(error or debug)",
    documentation: ".Q.bt[]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.btoa",
    detail: "b64 encode",
    documentation: ".Q.btoa[string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.bv",
    detail: "build schema for tables missing from partitions",
    documentation: ".Q.bv[<`>]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.Cf",
    detail: "create empty nested char file",
    documentation: ".Q.Cf[file]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.chk",
    detail: "fill HDB",
    documentation: ".Q.chk[dir]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.cn",
    detail: "count partitioned table",
    documentation: ".Q.cn[partitioned table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.D",
    detail: "partitions",
    documentation: ".Q.D",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.dd",
    detail: "join symbols",
    documentation: ".Q.dd[sym|dir;sym]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.def",
    detail: "provide defaults for .Q.opt",
    documentation: ".Q.def[default dict;params dict]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.dpft",
    detail: "save table",
    documentation: ".Q.dpft[dir;partition date;column sym;table sym]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.dpfts",
    detail: "save table with sym",
    documentation: ".Q.dpfts[dir;part;column sym;table sym;sym]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.dsftg",
    detail: "load process save",
    documentation:
      ".Q.dsftg[(dir;part;sym);(dir;offset;length);column syms;(types;widths);v1]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.en",
    detail: "enumerate varchar cols",
    documentation: ".Q.en[dir;table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.ens",
    detail: "enumerate against domain",
    documentation: ".Q.ens[dir;table;sym]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.f",
    detail: "format",
    documentation: ".Q.f[int;number]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.fc",
    detail: "parallel on cut(apply parallel)",
    documentation: ".Q.fc[v1;list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.ff",
    detail: "append columns",
    documentation: ".Q.ff[table;table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.fk",
    detail: "foreign key",
    documentation: ".Q.fk[column sym]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.fmt",
    detail: "format",
    documentation: ".Q.fmt[length;decimal;number]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.fps",
    detail: "streaming algorithm",
    documentation: ".Q.fps[v1;file]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.fqk",
    detail: "if system and built-in functions",
    documentation: ".Q.fqk[string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.fs",
    detail: "streaming algorithm",
    documentation: ".Q.fs[v1;file]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.fsn",
    detail: "streaming algorithm",
    documentation: ".Q.fsn[v1;file;chunk size]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.ft",
    detail: "apply simple",
    documentation: ".Q.ft[v1;keyed table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.fu",
    detail: "apply unique",
    documentation: ".Q.fu[v1;list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.gc",
    detail: "garbage collect",
    documentation: ".Q.gc[]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.gz",
    detail: "GZip",
    documentation: ".Q.gz[chars|bytes|(level;chars)|(level;bytes)]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.hdpf",
    detail: "save tables",
    documentation: ".Q.hdpf[hdb handle;dir;part;column sym]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.hg",
    detail: "HTTP get",
    documentation: ".Q.hg[url|string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.host",
    detail: "hostname",
    documentation: ".Q.host[ip int]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.hp",
    detail: "HTTP post",
    documentation: ".Q.hp[url|string;MIME string;query string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.id",
    detail: "sanitize",
    documentation: ".Q.id[sym|table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.ind",
    detail: "partitioned index",
    documentation: ".Q.ind[partitioned table;indices]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.j10",
    detail: "encode binhex",
    documentation: ".Q.j10[string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.j12",
    detail: "encode base64",
    documentation: ".Q.j12[string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.k",
    detail: "version",
    documentation: ".Q.k",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.l",
    detail: "load",
    documentation: ".Q.l[file|dir]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.M",
    detail: "long infinity",
    documentation: ".Q.M",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.MAP",
    detail: "maps partitions",
    documentation: ".Q.MAP[]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.nA",
    detail: "alphanums",
    documentation: ".Q.nA",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.opt",
    detail: "command parameters",
    documentation: ".Q.opt[strings|.z.x]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.P",
    detail: "segments",
    documentation: ".Q.P",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.par",
    detail: "locate partition",
    documentation: ".Q.par[dir;part;table sym]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.pd",
    detail: "modified partition locations",
    documentation: ".Q.pd",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.PD",
    detail: "partition locations",
    documentation: ".Q.PD",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.pf",
    detail: "partition field",
    documentation: ".Q.pf",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.pn",
    detail: "partition counts",
    documentation: ".Q.pn",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.prf0",
    detail: "code profiler",
    documentation: ".Q.prf0[pid]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.pt",
    detail: "partitioned tables",
    documentation: ".Q.pt",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.pv",
    detail: "modified partition values",
    documentation: ".Q.pv",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.PV",
    detail: "partition values",
    documentation: ".Q.PV",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.qp",
    detail: "is partitioned",
    documentation: ".Q.qp[table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.qt",
    detail: "is table",
    documentation: ".Q.qt[table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.res",
    detail: "keywords",
    documentation: ".Q.res",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.s",
    detail: "plain text",
    documentation: ".Q.s[any]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.s1",
    detail: "string representation",
    documentation: ".Q.s1[any]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.sbt",
    detail: "string backtrace",
    documentation: ".Q.sbt[backtrace object]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.sha1",
    detail: "SHA-1 encode",
    documentation: ".Q.sha1[string]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.trp",
    detail: "extend trap",
    documentation: ".Q.trp[v1;any;v2]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.ts",
    detail: "time and space",
    documentation: ".Q.ts[v;args]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.ty",
    detail: "type",
    documentation: ".Q.ty[list]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.u",
    detail: "is date based",
    documentation: ".Q.u",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.V",
    detail: "table to dict",
    documentation: ".Q.V[table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.v",
    detail: "value",
    documentation: ".Q.v[file|sym]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.view",
    detail: "subview",
    documentation: ".Q.view[parts]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.vp",
    detail: "missing partitions",
    documentation: ".Q.vp",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.w",
    detail: "memory stats",
    documentation: ".Q.w[]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.x",
    detail: "non-command parameters",
    documentation: ".Q.x",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.x10",
    detail: "decode binhex",
    documentation: ".Q.x10[long]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.x12",
    detail: "decode base64",
    documentation: ".Q.x12[long]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".Q.Xf",
    detail: "create file",
    documentation: ".Q.Xf[upper case char|type sym]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.a",
    detail: "Returns the IP address as a 32-bit integer.",
    documentation: ".z.a[{x;y}]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.ac",
    detail:
      "Http authenticate from cookie. Allows users to define custom code to extract Single Sign On (SSO) token cookies from the http header and verify it, decoding and returning the username, or instructing what action to take.",
    documentation: ".z.ac[]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.b",
    detail: "Returns the dependency dictionary.",
    documentation: ".z.b[]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.bm",
    detail:
      "KDB+ validates incoming ipc messages to check that data structures are well formed, reporting 'badMsg and disconnecting senders of malformed data structures. The raw message is captured for analysis via the callback .z.bm.",
    documentation: ".z.bm[]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.c",
    detail: "Physical core count.",
    documentation: ".z.c[]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.e",
    detail: "TLS connection status.",
    documentation: ".z.e[]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.exit",
    detail: "Exit behavior callback. Default: NOOP.",
    documentation: ".z.exit[]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.f",
    detail: "Returns the name of the q script as a symbol.",
    documentation: ".z.f[]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.h",
    detail: "Returns the host name as a symbol.",
    documentation: ".z.h[filename]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.i",
    detail: "Returns the process id as an integer.",
    documentation: ".z.i[]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.k",
    detail:
      "Returns the date on which the version of kdb+ being used was released.",
    documentation: ".z.k[x]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.K",
    detail:
      "Return the major version number of the version of kdb+ being used as a float.",
    documentation: ".z.K[table]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.l",
    detail: "Returns the license information as a list of strings.",
    documentation: ".z.l[]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.n",
    detail: "System GMT time (as timespan) in nanoseconds.",
    documentation: ".z.n[]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.N",
    detail: "System local time (as timespan) in nanoseconds.",
    documentation: ".z.N[]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.o",
    detail: "Return the kdb+ operating system version as a symbol.",
    documentation: '.z.o["Hello, world!"]',
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.p",
    detail: "System gmt timestamp in nanoseconds.",
    documentation: '.z.p["Hello, world!"]',
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.P",
    detail: "System localtime timestamp in nanoseconds.",
    documentation: ".z.P[]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.pc",
    detail: "Port close - Called AFTER a connection has been closed.",
    documentation: ".z.pc[]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.pg",
    detail:
      "Port get - When .z.pg is set, it is called with the object that is passed to this kdb+ session via a synchronous request. The return value, if any, is returned to the calling task.",
    documentation: ".z.pg[]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.pd",
    detail:
      "Peach handles - Indicating that N worker processes should be used for executing the function supplied to peach, kdb+ gets the handles to those worker processes by calling .z.pd[]. Syntax: .z.pd:`u#hopen each 20000+til 4",
    documentation: ".z.pd:5",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.ph",
    detail:
      "Port HttpGet - Called when a synchronous http request comes into the kdb+ session.",
    documentation: ".z.ph:10",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.pi",
    detail: "The default handler for input.",
    documentation: ".z.pi:2",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.pm",
    detail:
      "Pass http OPTIONS method through to .z.pm as (`OPTIONS;requestText;requestHeaderDict).",
    documentation: ".z.pm:80",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.po",
    detail:
      "Port open - Called when a connection to a kdb+ session has been initialized.",
    documentation: ".z.po:4",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.pp",
    detail:
      "Port post - Called when an http postrequest comes into the kdb+ session.",
    documentation: ".z.pp:3",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.ps",
    detail:
      "Port set - When .z.ps is set, it is called with the object that is passed to this kdb+ session via an asynchronous request. The return value is discarded.",
    documentation: ".z.ps:10",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.pw",
    detail:
      "Validate user - Called AFTER the -u/-U checks, and BEFORE .z.po when opening a new connection to a kdb+ session.",
    documentation: ".z.pw:80",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.q",
    detail: "Quiet mode",
    documentation: ".z.q[]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.s",
    detail:
      "Self - Returns the current function. Can be used to generate recursive function calls.",
    documentation: ".z.s[]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.ts",
    detail:
      "Function which is invoked on intervals of the timer variable (\t).",
    documentation: ".z.ts[]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.u",
    detail: "User ID - Returns user's name as a symbol.",
    documentation: ".z.u[]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.vs",
    detail:
      "Value set - Once .z.vs is defined, it is called with two arguments. The first argument is the symbol of the variable that is being modified and the second is the index.",
    documentation:
      '.z.vs:{[sym;idx;val] .Q.s[sym,"[",string idx,"]=",string val]}',
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.w",
    detail: "Connection handle, 0 for current session console.",
    documentation: ".z.w[]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.wc",
    detail:
      "Websocket close - Called after a websocket connection has been closed.",
    documentation:
      '.z.wc:{[handle;code;reason] .Q.s["Websocket closed: ",string code," ",reason]}',
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.wo",
    detail:
      "Websocket open - Called when a websocket connection to a kdb+ session has been initialized.",
    documentation:
      '.z.wo:{[handle;headers] .Q.s["Websocket opened: ",string handle]}',
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.W",
    detail:
      "Handles - Returns a dictionary of ipc handles with the number of bytes waiting in their output queues.",
    documentation: ".z.W[]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.ws",
    detail: "Websockets - Called when a message on a websocket arrives.",
    documentation: '.z.ws:{[handle;msg] .Q.s["Websocket message: ",msg]}',
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.x",
    detail: "Returns the command line arguments as a list of strings.",
    documentation: ".z.x[]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.X",
    detail:
      "Returns a list of char vectors of the raw, unfiltered cmd line with which kdb+ was invoked, including the name under which q was invoked as well as single-letter arguments.",
    documentation: ".z.X[]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.z",
    detail: "Returns UTC time as a datetime scalar.",
    documentation: ".z.z[]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.Z",
    detail: "Returns local time as a datetime scalar.",
    documentation: ".z.Z[]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.t",
    detail: "Returns UTC time as `time. Shorthand for `time$.z.z",
    documentation: ".z.t[]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.T",
    detail: "Returns local time as `time. Shorthand for `time$.z.Z",
    documentation: '.z.T:{[ex] .Q.s["Exception: ",string ex]}',
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.d",
    detail: "Returns UTC time as `date. Shorthand for `date$.z.z",
    documentation: ".z.d[]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.D",
    detail: "Returns local time as `date. Shorthand for `date$.z.Z",
    documentation: ".z.D[]",
    kind: CompletionItemKind.Variable,
  },
  {
    label: ".z.zd",
    detail:
      "Zip defaults - If defined, is an integer list of default parameters for logical block size, compression algorithm and compression level that apply when saving to files with no file extension.",
    documentation: ".z.zd:100 1 9",
    kind: CompletionItemKind.Variable,
  },
];
