# This workflow runs the tests across Linux, Mac, Windows

name: KX VS Code CI Testing

on:
  pull_request:
    branches:
      - dev
      - main
    paths-ignore: ["**/*.md"]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm ci
      - run: xvfb-run -a npm run coverage
        if: runner.os == 'Linux'
      - run: npm test
        if: runner.os != 'Linux'

      - name: Code coverage summary
        if: runner.os == 'Linux'
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ./coverage-reports/cobertura-coverage.xml
          badge: true
          format: markdown
          hide_branch_rate: true
          hide_complexity: true
          thresholds: "30 80"
          output: "both"

      - name: Write Coverage to Job Summary
        if: runner.os == 'Linux'
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

      - name: Upload lcov result for app-sec job
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v3
        with:
          name: lcov
          path: coverage-reports/lcov.info
          retention-days: 1

  app-sec:
    needs: test
    if: "! github.event.pull_request.head.repo.fork "
    uses: ./.github/workflows/app-sec-template.yml
    with:
      github_ref: ${{ github.ref_name }}
    secrets: inherit
