# This workflow runs the tests across Linux, Mac, Windows

name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Package
        run: npx vsce package
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: kdb
          path: ./kdb-*.vsix
      # - name: Publish
      #   if: github.ref == 'refs/heads/main'
      #   run: |
      #     vsce publish -p ${{ secrets.VSCE_PAT }}
