name: KX VS Code Release Workflow

on:
  push:
    branches:
      - dev
      - main

env:
  NODE_ENV: production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci --include=dev
      - name: Build VSIX file
        run: npm run build
      - name: Run Tests
        run: xvfb-run -a npm run coverage
      - name: Packaging
        run: npm run package
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: KDB-VSCode-Extension
          path: ./kdb-*vsix
          retention-days: 1
      - name: Upload lcov result for app-sec job
        uses: actions/upload-artifact@v3
        with:
          name: lcov
          path: coverage-reports/lcov.info
          retention-days: 1

  app-sec:
    needs: build
    uses: ./.github/workflows/app-sec-template.yml
    with:
      github_ref: ${{ github.ref_name }}
    secrets: inherit

  release:
    runs-on: ubuntu-latest
    needs: app-sec
    steps:
      - name: Download VSIX file from build job
        uses: actions/download-artifact@v3
        with:
          name: KDB-VSCode-Extension
      - name: Release to Portal
        run: |
          NOW=$(date +'%Y%m%dT%H%M%S')
          curl -L -s --fail-with-body -D /dev/stderr --oauth2-bearer ${{ secrets.kx_downloads_token_prod }} \
          -H 'content-type: application/octet-stream' \
          --upload-file ./kdb-*.vsix \
          https://portal.dl.kx.com/assets/raw/kdb-vscode/${{ github.ref_name }}/kdb-${{ github.ref_name }}.$NOW.vsix
